[package]
name = "tilepad-plugin-sdk"
description = "Plugin SDK for tilepad"
version = "0.0.0"
edition = "2021"
keywords = ["EA", "PocketRelay", "MassEffect"]
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/tilepad/tilepad-desktop"

[dependencies]
